name: Demo vulnerable workflow
on:
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  vuln_job:
    runs-on: ubuntu-latest
    steps:
     # Checkout used for demonstration purposes
      - uses: actions/checkout@v2
      - run: |
         echo "ISSUE TITLE: ${{github.event.issue.title}}"
         echo "ISSUE DESCRIPTION: ${{github.event.issue.body}}"
      - run: |
         curl -X POST -H "Authorization: Token ${{ secrets.GIT_AUTH_TOKEN }}" -d '{"labels": ["New Issue"]}' ${{ github.event.issue.url }}/labels
